@"
name: Bug report
description: Report a reproducible bug
title: "[bug]: "
labels: [bug]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: Clear steps to reproduce, what you expected vs. what you saw.
      placeholder: Steps, lever numbers, logs/snippets
    validations:
      required: true
"@ | Set-Content .github\ISSUE_TEMPLATE\bug_report.yml -Encoding UTF8 -Force


